name: Discord Notification

on:
  push:
    branches:
      - main

jobs:
  send_commit_message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get latest commit message
        id: commit_message
        run: echo "::set-output name=message::$(git log -1 --pretty=format:'%s')"

      - name: Send message to Discord
        uses: Ilshidur/action-discord@master
        with:
          args: ${{ steps.commit_message.outputs.message }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
