name: Discord Notification

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  send_pr_message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Send message to Discord
        uses: Ilshidur/action-discord@master
        with:
          args: |
            Pull Request #${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}
            Created by: ${{ github.event.pull_request.user.login }}
            URL: ${{ github.event.pull_request.html_url }}
            Prod site: "https://rvndyr.com/"
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
